# Generated by Django 4.0.5 on 2022-06-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
